### ISSUE TITLE
how to reset 

### ISSUE THREAD

**Issue by exciar** [rusq/wipemychat#9]
I put the wrong credentials, tried deleting still uses the same credentials so it won't work

**Comment by rusq** [comment]
Hey @exciar,

Have you tried running the following?
```
wipemychat -reset
```

**Comment by rusq** [comment]
I'll explain how the authentication works, just so that you understand why deleting the credentials file did not work.

It consists of 2 parts:
1. your app hash and app secret
2. your telegram login details

app hash and app secret are constant, but you can have more than one phone number used with the same app hash and app secret, hence they are stored separately.  App hash and app secret are stored in the OS cache directory (i.e. `~/Library/Caches/wipemychat` on mac), and the credentials are stored alongside the program executable.

In hindsight, this may not be the best way, but at the time of writing I thought it's a good idea.

Let me know if reset helps, it removes both files.

**Comment by exciar** [comment]
> Hey @exciar,
> 
> Have you tried running the following?
> 
> ```
> wipemychat -reset
> ```

how do I run this

**Comment by rusq** [comment]
When you say "how do I run this", are you asking how to run a command with a parameter?

[Try this](https://support.apple.com/en-au/guide/terminal/apdb66b5242-0d18-49fc-9c47-a2498b7c91d5/mac) maybe

**Comment by exciar** [comment]
im on windows

**Comment by rusq** [comment]
@exciar, let me ask you:  do you expect me to explain how to run commands on windows, or I can trust you figuring it out?

**Comment by exciar** [comment]
> @exciar, let me ask you: do you expect me to explain how to run commands on windows, or I can trust you figuring it out?

I just made a clean install of windows again so I can put the right credentials, thanks for trying to help me

**Comment by rusq** [comment]
No problem, that seems like a huge effort just to get it going, hope this was not the only reason you did it?

Yes, it should work fine.  If you run into this again for some reason, I'm going to assume that you unpacked it to your "Downloads\wipemychat" folder.
1. Press Cmd+R
2. type "cmd" and press Enter, command prompt window will pop up
3. Navigate to your downloads folder, you can use "dir" to list the contents of the current directory and "cd" to Change Directory to one of the ones you see in the list.  The fastest way is to type "cd \Users\<your_username>\Downloads"
4. Once you made it to downloads, change directory to wipemychat, i.e. "cd wipemychat".  Make sure that the prompt says something like "C:\Users\<yourname>\Downloads\wipemychat>_" where _ is the cursor
5. type: ".\wipemychat.exe -reset", this will reset the credentials
6. You can start  over by typing ".\wipemychat.exe" and login again.

My learning from this issue that looks like wipemychat needs a menu
